### ISSUE TITLE
Capacitor Section: native configuration not working?

### ISSUE THREAD

**Issue by HeikoKanzler** [ionic-team/vscode-extension#53] opened 2022-07-21 08:03 UTC
I have a new project using Ionic React / Capacitor which works so far (runs on the device), but I recently checked the extension and the Capacitor entries are empty except the Display name.

If I want to enter something into Bundle ID (which is already in the capacitor.config.ts), the version or build number, it's not stored somewhere. 
![CleanShot 2022-07-21 at 09 59 48](https://user-images.githubusercontent.com/5279575/180162342-10ffb73c-fba9-45c6-8eac-f6ce2c3c5f8b.jpg)

Any ideas?

**Comment by dtarnawsky** [comment] 2022-07-21 13:52
Hi @HeikoKanzler,

Thanks so much for the bug report. I isolated it down to when you only add the iOS platform and not Android in a project. The problem is now fixed and has been released as part of v1.8.13 which VS Code should pick up in the next 30 minutes or so.

**Closed as completed by dtarnawsky** 2022-07-21 13:52 UTC
Labels: bug, next release

**Comment by HeikoKanzler** [comment] 2022-07-21 14:23
Awesome, thank you.
