### ISSUE TITLE
In a Monorepo extension detects wrong project as ionic app, and then does not search for other apps

### ISSUE THREAD

**Issue by distante** [ionic-team/vscode-extension#131] opened 2023-08-11 10:49 UTC
I have an NX monorepo with just one Ionic app. For some reason, the extension detects an empty project as an Ionic project, what is not that important, but the big problem, is that it stops trying to find another ionic apps.

If I manually complete delete the wrongly detected app project, the extension finds my real app.

**Comment by dtarnawsky** [comment] 2023-08-15 19:23
Can you provide a sample repo that exhibits the problem? Quite often the problem is misconfiguration of NX project.json's or workspaces that cause issues like this.

**Comment by distante** [comment] 2023-08-16 06:11
Will try to build once since I can not share the project I am working on.

I once fixed a problem like this in this same extension but that was when the code was open.

**Comment by dtarnawsky** [comment] 2023-08-16 13:05
One thing you can do is supply the folder/config structure but without the code: ie remove the source code files and leave the config files and folders. That way you aren't supplying any source code.

**Comment by dtarnawsky** [comment] 2023-09-08 18:03
Without a way to repro I need to close this ticket.

**Closed as not planned by dtarnawsky** 2023-09-08 18:03 UTC
