### ISSUE TITLE
Focus on "output" window every time it rebuilds the project

### ISSUE THREAD

**Issue by HerniHdez** [ionic-team/vscode-extension#30] opened 2022-03-31 15:00 UTC
After updating yesterday to the latest version it does something very strange, when I type some code and it auto-rebuilds the project, it changes the focus to the "output" window, so I spend more time clicking to return to the code than writing it.

![image](https://user-images.githubusercontent.com/51020632/161086509-683fb310-1318-4bd1-baa3-7566dc0003f8.png)

If you need to see an online demo just tell me.

**Comment by dtarnawsky** [comment] 2022-03-31 15:30
Hi @HerniHdez, can you verify that you are using version 1.4.4 of the extension?

Also, the check to see if the output window is already focused does this check:
`.document?.uri?.scheme == 'output')`

I'm wondering where the issue relates back to language as it looks like your output window is named salida.

**Comment by HerniHdez** [comment] 2022-03-31 16:05
Hello,

Yes, I have the version 1.4.4 installed, and yes I have the VSCode language set to "Spanish".
![image](https://user-images.githubusercontent.com/51020632/161096523-69df2584-e87a-4588-acb5-76567664e3dc.png)

And yes, I have the VSCode language set to "Spanish", can be that?

Not sure how to execute the check, but I know the "output" window is focus because after losing the focus on the code, if I press the "backspace" key it shows a message on the "output" window saying I can't edit a read-only editor.
![image](https://user-images.githubusercontent.com/51020632/161098922-4c5b235c-0705-487e-86dd-1343a06a5a0b.png)


I have just checked that if I run on terminal "ionic serve" instead of using the extension's option "Run On Web", it works fine, the only difference I see is that I get the output on the "terminal" window, but it is normal.

**Comment by dtarnawsky** [comment] 2022-03-31 21:33
Hi @HerniHdez , I tested VS code in Spanish, what I found was that if you had an item like "Terminal" focused previously then the focus would change to "Output", but if you had "Output" already focused then the focus would not be lost from the editor. Let me know if this is the case.

**Comment by HerniHdez** [comment] 2022-04-04 11:21
Hi @dtarnawsky, that was not the problem, I saw that behavior before and I think it may be logical.

I'm trying to reproduce it again without success, I'm not sure if I was running more than one "ionic serve" from the extension, but as I told you it hasn't happened again... weird. I'll keep messing around to see if I can figure it out.

**Comment by dtarnawsky** [comment] 2022-04-05 13:41
HI @HerniHdez, this specific scenario is now fixed in 1.4.4 but there was scenario where multiple tasks like "ionic serve" could be launched causing some odd behavior like this - that problem is fixed in 1.5.0 which is now in "pre-release" and you can install manually from the extension marketplace. For now, I'll close this issue. If you are able to reproduce the issue then please do reply.

**Closed as completed by dtarnawsky** 2022-04-05 13:41 UTC
