### ISSUE TITLE
Update Sentry support to support Capacitor v5

### ISSUE THREAD

**Issue by RobSchilderr** [ionic-team/vscode-extension#122] opened 2023-06-14 09:22 UTC
**Is your feature request related to a problem? Please describe.** The latest Sentry update (0.12.0) has been released 10 days ago, but currently only `@sentry/capacitor 0.11.3` is supported, according to the website. Users who would like to take advantage of the new Sentry features cannot do so, as there is no support for it with the current `@sentry/capacitor` version. Furthermore, Sentry 0.12.0 adds support for Capacitor v5, which is important as the rest of the Capacitor plugins support v5.

**Describe the solution you'd like** Update the `@sentry/capacitor` package support to support Sentry 0.12.0

**Comment by dtarnawsky** [comment] 2023-06-14 13:07
Thanks for the report @RobSchilderr,

Looks like there is a plugin that has some unexpected data in its last release and is breaking the registry:
[https://github.com/ionic-team/capacitor-plugin-registry/actions/runs/5262931724/jobs/9512590423](https://github.com/ionic-team/capacitor-plugin-registry/actions/runs/5262931724/jobs/9512590423)

I'll get it fixed today...

**Comment by dtarnawsky** [comment] 2023-06-14 13:51
And the issue is now fixed.

**Closed as completed by dtarnawsky** 2023-06-14 13:51 UTC
